version: '3.8'
services:
  dev:
    command: python -m http.server
    image: python
    network_mode: bridge
    working_dir: /epaper
    volumes:
      - ./:/epaper
      - root:/root
volumes:
  root:
